### PR TITLE
add reverse symlinked files.

### PR DESCRIPTION
**Pull request by erip**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/master/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?

Fixes CLI issues with Windows builds.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by erip** [comment]
I think this is good to go - WDYT, @myleott?

**Comment by myleott** [comment]
Sorry the previous one had some internal test failures that blocked the merge, but I think they were unrelated. Let's merge this one.

**Comment by myleott** [comment]
Hmm, it's still failing some internal tests -- I think the internal build system doesn't handle the symlinks properly either. I'll probably need to recreate this PR.

**Comment by erip** [comment]
My approach has basically been...

```
mv generate.py interactive.py preprocess.py validate.py train.py score.py eval_lm.py fairseq_cli
rm fairseq_cli/setup.py
for i in `ls fairseq_cli`; do ln -s fairseq_cli/$i $i; done
rm __init__.py
```

**Comment by erip** [comment]
@myleott let me know how I can help!

**Comment by myleott** [comment]
Still working on it... I need to split it into three separate PRs (one to delete current symlinks, one to rename, one to add new symlinks). But the middle PR makes the internal build system very unhappy, so I'm having to move a bunch of pointers to fairseq_cli. Hopefully can get it figured out today...

**Comment by erip** [comment]
@myleott if you've gotten any positive feedback from the internal circulation about the `fairseq.cli` idea, I'd be happy to push on that, which I think would be a more continuous overlay of commits.

**Pull request closed without merging**
