### PR TITLE
WIP: TPU support

### PR DESCRIPTION
**Pull request by myleott**

### CODE REVIEW

**Comment by frankxu2004** [comment]
Hi myleott,

This seems really interesting and although it's WIP I still decided to give it a try on Cloud TPUs by pretraining Roberta model.

From what I see here, it not using 8 TPU cores as the --distributed-world-size seems to always be 1?

**Comment by myleott** [comment]
Cool, thanks for testing this out! Please try the latest version in this PR.

To get started you can use the dummy_masked_lm task to make sure things are working with fake data:
```bash
python train.py \
  --distributed-world-size 8 --bf16 \
  --num-workers 2 --no-save --disable-validation \
  --task dummy_masked_lm --dataset-size 1000000 --dict-size 49995 \
  --tokens-per-sample 512 \
  --criterion masked_lm \
  --arch roberta_base \
  --optimizer sgd --lr 1e-4 \
  --max-sentences 8 --update-freq 1 \
  --log-format json --log-interval 10
```

Later you can try a real training run:
```
python train.py /path/to/your/data \
  --distributed-world-size 8 --bf16 \
  --num-workers 2 --skip-invalid-size-inputs-valid-test \
  --task masked_lm --sample-break-mode none --tokens-per-sample 512 \
  --criterion masked_lm \
  --arch roberta_base \
  --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-06 --clip-norm 0.0 \
  --lr-scheduler polynomial_decay --lr 0.0006 --warmup-updates 3125 --total-num-update 100000 \
  --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
  --max-sentences 8 --update-freq 1 \
  --max-update 100000 \
  --log-format json --log-interval 10
```

Some things to note:
* you don't need to set `XLA_USE_BF16=1`, if you pass the `--bf16` flag then fairseq will do proper mixed precision training
* it's currently required that you set `--sample-break-mode none` so that the batch dimensions are exactly the same for every batch, otherwise you'll get lots of XLA compiles and it will slow down significantly (that might be the reason for the hang you observed before)
* it's recommended to set `--log-interval` to some larger value (>= 10), since lower values will slow down XLA. Note that the words-per-second (wps) that's reported will be shrunk by the same amount. So if you do `--log-interval=10`, then you should multiply the reported wps by 10 to get the real figure.
* setting `--num-workers=2` or higher is good

**Comment by frankxu2004** [comment]
Thanks for the pointer, I really appreciate it and will try it out very soon.

A quick question, do you have any time estimate like how long will it take for each step or each epoch based on your own test run on 1 TPU node? It would be great to now the numbers so I could test it out and see if our performances match!

**Comment by frankxu2004** [comment]
Hi myleott,

I tried training on WikiText-103 dataset as shown in the example for pretraining from scratch with roberta https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md, but after a few steps, it throws an error. I am using your suggested command to run it, and the dummy test run seems fine after several minutes though. Do you have any idea what this error might be? Thanks!

```
INFO:train:epoch 001:   1740 / 1797 loss=11.603, ppl=3110.27, wps=14307, ups=2.18, wpb=65536, bsz=128, num_updates=1740, lr=8.7e-05, gnorm=1.369, clip=0, train_wall=314, wall=1041
INFO:train:epoch 001:   1750 / 1797 loss=11.593, ppl=3089.82, wps=14307.1, ups=2.18, wpb=65536, bsz=128, num_updates=1750, lr=8.75e-05, gnorm=1.365, clip=0, train_wall=315, wall=1046
INFO:train:epoch 001:   1760 / 1797 loss=11.584, ppl=3070.37, wps=14306.1, ups=2.18, wpb=65536, bsz=128, num_updates=1760, lr=8.8e-05, gnorm=1.362, clip=0, train_wall=317, wall=1050
INFO:train:epoch 001:   1770 / 1797 loss=11.575, ppl=3051.23, wps=14306.4, ups=2.18, wpb=65536, bsz=128, num_updates=1770, lr=8.85e-05, gnorm=1.358, clip=0, train_wall=318, wall=1055
INFO:train:epoch 001:   1780 / 1797 loss=11.566, ppl=3031.83, wps=14307.1, ups=2.18, wpb=65536, bsz=128, num_updates=1780, lr=8.9e-05, gnorm=1.354, clip=0, train_wall=319, wall=1059
INFO:train:epoch 001:   1790 / 1797 loss=11.557, ppl=3013.62, wps=14306.9, ups=2.18, wpb=65536, bsz=128, num_updates=1790, lr=8.95e-05, gnorm=1.35, clip=0, train_wall=321, wall=1064
2020-03-18 05:24:51.525460: E    2248 tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: at::canCast( resultType, out.scalar_type())
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()

        torch_xla::AtenXlaType::mul_(at::Tensor&, at::Tensor const&)





        PyCFunction_Call
        PyObject_Call
....
.....
.....
*** End stack trace ***

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/home/frank/dev/fairseq/fairseq_cli/train.py", line 309, in distributed_main
    main(args, init_distributed=True)
  File "/home/frank/dev/fairseq/fairseq_cli/train.py", line 104, in main
    train(args, trainer, task, epoch_itr)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/frank/dev/fairseq/fairseq_cli/train.py", line 198, in train
    log_output = trainer.train_step(samples)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/frank/dev/fairseq/fairseq/trainer.py", line 381, in train_step
    sample_size *= 0.  # multiply by 0 to preserve device
RuntimeError: torch_xla/csrc/aten_xla_type.cpp:117 : Check failed: at::canCast( resultType, out.scalar_type())

```

**Pull request closed without merging**
