### PR TITLE
refactor namespaces in optimizer

### LINKED ISSUE #1672: Replace use of argparse.Namespace with named args and kwargs where possible.
## 🚀 Feature Request

Remove `argparse.Namespace` parameter passing where possible.

### Motivation

Using `args` makes code unclear to read because it couples implementations with `argparse` tightly. Functions and classes should rely on what they need to function and no more. 

### Pitch

With the exception of `classmethod`s, arguments to functions and methods should be named and explicitly passed in. This makes the code:

- More readable -- no more cluttering the code with `args.X` in implementations that _only_ care about `X`
- More testable -- argparse is a runtime concern and won't/shouldn't be needed in tests
- More portable -- if I want to use a class from `fairseq` in some other code, I don't need to "mock" argument parsing logic.
- Less tightly coupled -- instead of guessing why some call-site passed in `args`, I know exactly what the minimal information required to compute some function will be.

### Alternatives

Leave the code as is. 😄 

### Additional context

As I begin looking at the refactor for #1648, I see `args` buried deep in the code. This refactor would be much easier if this were implemented first.

### PR DESCRIPTION
**Pull request by erip**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/master/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes #1672 in part (part 3: [context](https://github.com/pytorch/fairseq/pull/1714#issuecomment-587507040))

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by erip** [comment]
@myleott I've added a legacy optimizer interface - is this sort of what you had in mind?

**Comment by myleott** [comment]
Yes, exactly. I'll pick up working on this over the next couple days :)

**Comment by erip** [comment]
Awesome! I can continue adding legacy interfaces for the other components. Thank you. 🔥

**Comment by erip** [comment]
@myleott anything you need from me to help with this? I recall this was one of the less controversial open PRs. 😄

**Pull request closed without merging**
