### PR TITLE
add other platforms to CI.

### PR DESCRIPTION
**Pull request by erip**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/master/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?

Runs CI for `fairseq` on all major platforms provided by GitHub actions.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by erip** [comment]
This is sort of painful because the Windows tests can't find the appropriate MSVC compiler. I'll have to play with this, but will call it a WIP for now.

**Comment by erip** [comment]
@myleott this is a sort of chicken and egg since Windows is broken. One thing we could do is merge this and _allow_ Windows builds to fail for now. This gives fairseq contributors the chance to fix the Windows build with a separate PR and get feedback as they make commits. 

Since Unix has been the main target, do you think this is an OK way to proceed? I'd love to get Windows builds at parity (and level of attention) as other envs. 😄

**Comment by myleott** [comment]
Yes, please update to allow a broken Windows build and we can merge this.

Separately, I'll work on #1622 later today.

**Comment by erip** [comment]
I [pulled a sneaky on ya](https://www.youtube.com/watch?v=pg0_a2_7a1c) and added Python 3.7 to the matrix. This PR basically does that and also prevents fail-fast mode, which will basically let stages fail without preventing other stages from building. This means that Windows can (and will) fail -- that failure will be reported in the build above. As long as only Windows is failing, you should feel as comfortable merging commits as you ever have. Eventually we can even fix the Windows build and re-enable fail-fast. 😄

**Pull request closed without merging**
