### PR TITLE
[WIP] refactor namespaces

### LINKED ISSUE #1672: Replace use of argparse.Namespace with named args and kwargs where possible.
## 🚀 Feature Request

Remove `argparse.Namespace` parameter passing where possible.

### Motivation

Using `args` makes code unclear to read because it couples implementations with `argparse` tightly. Functions and classes should rely on what they need to function and no more. 

### Pitch

With the exception of `classmethod`s, arguments to functions and methods should be named and explicitly passed in. This makes the code:

- More readable -- no more cluttering the code with `args.X` in implementations that _only_ care about `X`
- More testable -- argparse is a runtime concern and won't/shouldn't be needed in tests
- More portable -- if I want to use a class from `fairseq` in some other code, I don't need to "mock" argument parsing logic.
- Less tightly coupled -- instead of guessing why some call-site passed in `args`, I know exactly what the minimal information required to compute some function will be.

### Alternatives

Leave the code as is. 😄 

### Additional context

As I begin looking at the refactor for #1648, I see `args` buried deep in the code. This refactor would be much easier if this were implemented first.

### PR DESCRIPTION
**Pull request by erip**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/master/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes #1672 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by erip** [comment]
Tapping out for tonight. Remaining refactors to make:

- [ ] `FairseqTask`s

- [ ] `Fairseq...Model`s

- [ ] `FairseqEncoder`s

- [ ] `FairseqTokenizer`s

I'll try to tackle these this week.

**Comment by myleott** [comment]
This is looking pretty good so far, thanks!

One comment: I don't think we should do the full refactoring in a single PR. Let's have one for optimizers, one for tasks, one for models, etc.

The reason is that before we can merge, we need to import the PR and run internal unit/integration tests, which usually requires some additional changes on the FB side. If we can keep these more focused it will make that part easier for me :)

**Comment by erip** [comment]
Ok, can do. I'll try to cherry-pick these into a separate branch tonight.

**Comment by myleott** [comment]
Awesome, I'll start running these against the internal unit tests :)

**Comment by erip** [comment]
@myleott looks like they're all good - anything you need from me?

**Comment by erip** [comment]
@myleott sorry to keep harassing you - since these files tend to be hot, I wanted to see if there's anything you need from me in order to merge them so we can prevent the merge-conflict=>reimport loop. 😄

**Pull request closed without merging**
